Blast\Bundle\DoctrineSessionBundle\Entity\Session:
    type: entity
    table: blast_session
    id:
        id:
          type: integer
          generator:
            strategy: AUTO
    fields:
        sessionId:
            type: string
            length: 255
            column: session_id
        data:
            type: blob
            nullable: true
        createdAt:
            type: datetime
        expiresAt:
            type: datetime
    indexes:
        blast_session_session_id_index:
            columns: [session_id]
    lifecycleCallbacks: {  }
