# Package `sllh/php-cs-fixer-styleci-bridge` is required to get it working.

preset: psr2

enabled:
# - class_keyword_remove
# - combine_consecutive_unsets
# - long_array_syntax
# - newline_after_open_tag
  - no_php4_constructor
#  - no_useless_else

#  - ordered_class_elements
#  - ordered_use
# Comment strict rules for the moment. Should be uncomment later to see StyleCI PR results
#  - strict
#  - strict_param
#  - php_unit_construct
#  - php_unit_strict

disabled:
  - phpdoc_inline_tag
  - concat_without_spaces

finder:
  exclude:
    - 'Tests/Fixtures'
