<?php

namespace Blast\DoctrineSessionBundle\Entity\Test\Unit;

use Blast\DoctrineSessionBundle\Entity\Session;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 16:46:28.
 */

use PHPUnit\Framework\TestCase;

class SessionTest extends TestCase
{
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new Session;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::setSessionId
     * @todo   Implement testSetSessionId().
     */
    public function testSetSessionId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::getSessionId
     * @todo   Implement testGetSessionId().
     */
    public function testGetSessionId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::getData
     * @todo   Implement testGetData().
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::getCreatedAt
     * @todo   Implement testGetCreatedAt().
     */
    public function testGetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::setCreatedAt
     * @todo   Implement testSetCreatedAt().
     */
    public function testSetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::setExpiresAt
     * @todo   Implement testSetExpiresAt().
     */
    public function testSetExpiresAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Entity\Session::getExpiresAt
     * @todo   Implement testGetExpiresAt().
     */
    public function testGetExpiresAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
