<?php
namespace Blast\Tests\Functional;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-24 at 16:53:17.
 */
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Input\ArrayInput;
use Blast\DoctrineSessionBundle\Command\CollectGarbageCommand;

class CollectGarbageCommandTest extends BlastTest
{
    /**
     * @var CollectGarbageCommand
     */
   # protected $object;
   
   
    protected function setUp()
    {
        $this->createDatabase();
        $this->updateSchema();
        $this->validateSchema();
    }
    
    protected function tearDown()
    {
        $this->dropDatabase();
    }

    public function testEmpty()
    {
        /* trigger setup */
    }
}
