<?php

namespace Blast\DoctrineSessionBundle\DependencyInjection\Test\Unit;

use Blast\DoctrineSessionBundle\DependencyInjection\BlastDoctrineSessionExtension;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 16:46:28.
 */

use PHPUnit\Framework\TestCase;

class BlastDoctrineSessionExtensionTest extends TestCase
{
    /**
     * @var BlastDoctrineSessionExtension
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new BlastDoctrineSessionExtension;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Blast\DoctrineSessionBundle\DependencyInjection\BlastDoctrineSessionExtension::doLoad
     * @todo   Implement testDoLoad().
     */
    public function testDoLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
