<?php

namespace Blast\DoctrineSessionBundle\DependencyInjection\Test\Unit;

use Blast\DoctrineSessionBundle\DependencyInjection\Configuration;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 16:46:28.
 */

use PHPUnit\Framework\TestCase;

class ConfigurationTest extends TestCase
{
    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new Configuration;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Blast\DoctrineSessionBundle\DependencyInjection\Configuration::getConfigTreeBuilder
     * @todo   Implement testGetConfigTreeBuilder().
     */
    public function testGetConfigTreeBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
