<?php

namespace Blast\DoctrineSessionBundle\Handler\Test\Unit;

use Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 16:46:28.
 */

use PHPUnit\Framework\TestCase;

class DoctrineORMHandlerTest extends TestCase
{
    /**
     * @var DoctrineORMHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new DoctrineORMHandler;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::gc
     * @todo   Implement testGc().
     */
    public function testGc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::open
     * @todo   Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::read
     * @todo   Implement testRead().
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Blast\DoctrineSessionBundle\Handler\DoctrineORMHandler::write
     * @todo   Implement testWrite().
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
